export const mockProceduresList: any = [
    {
        "id": 0,
        "benClassId": null,
        "benClassName": null,
        "isSubclass": null,
        "benClassIdSub": null,
        "benClassNameSub": null,
        "isCustom": null,
        "procedureId": 659,
        "code": "D0120",
        "description": "Periodic oral eval",
        "shortDescription": "Periodic oral eval",
        "dateFrom": "1970-01-01T00:00:00-05:00",
        "dateTo": null,
        "serviceType": 10921,
        "serviceTypeName": "Oral Evaluation",
        "neddCoverage": 11001,
        "neddCoverageName": "NEDD Covered",
        "ageLow": null,
        "ageHigh": null,
        "treatmentArea": null,
        "treatmentAreaName": null,
        "surfaceArea": null,
        "surfaceAreaName": null,
        "treatmentAreaDetailList": [{
            id: 1000,
            description: 'AA'
        }, {
            id: 1001,
            description: 'BB'
        }, {
            id: 1002,
            description: 'CC'
        }]
    },
    {
        "id": 0,
        "benClassId": null,
        "benClassName": null,
        "isSubclass": null,
        "benClassIdSub": null,
        "benClassNameSub": null,
        "isCustom": null,
        "procedureId": 661,
        "code": "D0140",
        "description": "Ltd oral eval prob focus",
        "shortDescription": "Ltd oral eval prob focus",
        "dateFrom": "1970-01-01T00:00:00-05:00",
        "dateTo": null,
        "serviceType": 10921,
        "serviceTypeName": "Oral Evaluation",
        "neddCoverage": 11001,
        "neddCoverageName": "NEDD Covered",
        "ageLow": null,
        "ageHigh": null,
        "treatmentArea": null,
        "treatmentAreaName": null,
        "surfaceArea": null,
        "surfaceAreaName": null,
        "treatmentAreaDetailList": null
    },
    {
        "id": 0,
        "benClassId": null,
        "benClassName": null,
        "isSubclass": null,
        "benClassIdSub": null,
        "benClassNameSub": null,
        "isCustom": null,
        "procedureId": 27,
        "code": "D0145",
        "description": "Oral eval pts under 3",
        "shortDescription": "Oral eval pts under 3",
        "dateFrom": "2007-01-01T00:00:00-05:00",
        "dateTo": null,
        "serviceType": 10921,
        "serviceTypeName": "Oral Evaluation",
        "neddCoverage": 11001,
        "neddCoverageName": "NEDD Covered",
        "ageLow": null,
        "ageHigh": 2,
        "treatmentArea": null,
        "treatmentAreaName": null,
        "surfaceArea": null,
        "surfaceAreaName": null,
        "treatmentAreaDetailList": null
    },
    {
        "id": 0,
        "benClassId": null,
        "benClassName": null,
        "isSubclass": null,
        "benClassIdSub": null,
        "benClassNameSub": null,
        "isCustom": null,
        "procedureId": 662,
        "code": "D0150",
        "description": "Comprehensive oral eval",
        "shortDescription": "Comprehensive oral eval",
        "dateFrom": "1970-01-01T00:00:00-05:00",
        "dateTo": null,
        "serviceType": 10921,
        "serviceTypeName": "Oral Evaluation",
        "neddCoverage": 11001,
        "neddCoverageName": "NEDD Covered",
        "ageLow": null,
        "ageHigh": null,
        "treatmentArea": null,
        "treatmentAreaName": null,
        "surfaceArea": null,
        "surfaceAreaName": null,
        "treatmentAreaDetailList": null
    },
    {
        "id": 0,
        "benClassId": null,
        "benClassName": null,
        "isSubclass": null,
        "benClassIdSub": null,
        "benClassNameSub": null,
        "isCustom": null,
        "procedureId": 663,
        "code": "D0160",
        "description": "Detailed/exten oral eval",
        "shortDescription": "Detailed/exten oral eval",
        "dateFrom": "1970-01-01T00:00:00-05:00",
        "dateTo": null,
        "serviceType": 10921,
        "serviceTypeName": "Oral Evaluation",
        "neddCoverage": 11001,
        "neddCoverageName": "NEDD Covered",
        "ageLow": null,
        "ageHigh": null,
        "treatmentArea": null,
        "treatmentAreaName": null,
        "surfaceArea": null,
        "surfaceAreaName": null,
        "treatmentAreaDetailList": null
    },
    {
        "id": 0,
        "benClassId": null,
        "benClassName": null,
        "isSubclass": null,
        "benClassIdSub": null,
        "benClassNameSub": null,
        "isCustom": null,
        "procedureId": 664,
        "code": "D0170",
        "description": "Re-eval ltd prob focus",
        "shortDescription": "Re-eval ltd prob focus",
        "dateFrom": "1970-01-01T00:00:00-05:00",
        "dateTo": null,
        "serviceType": 10921,
        "serviceTypeName": "Oral Evaluation",
        "neddCoverage": 11001,
        "neddCoverageName": "NEDD Covered",
        "ageLow": null,
        "ageHigh": null,
        "treatmentArea": null,
        "treatmentAreaName": null,
        "surfaceArea": null,
        "surfaceAreaName": null,
        "treatmentAreaDetailList": null
    }
];

export const mockProcedure: Procedure =
{
    id: 1,
    benClassId: 5,
    benClassName: 'null',
    isSubclass: 0,
    benClassIdSub: 6,
    benClassNameSub: 'null',
    isCustom: 0,
    procedureId: 659,
    code: 120,
    description: "Periodic oral eval",
    shortDescription: "Periodic oral eval",
    dateFrom: new Date("1970-01-01T00:00:00-05:00"),
    dateTo: null,
    serviceType: 10921,
    serviceTypeName: "Oral Evaluation",
    neddCoverage: 11001,
    neddCoverageName: "NEDD Covered",
    ageLow: 2,
    ageHigh: 5,
    treatmentArea: 150,
    treatmentAreaName: 'null',
    treatmentAreaDetailList: 'null'
}
export const mockProcedure2: Procedure =
{
    id: 2,
    benClassId: 5,
    benClassName: 'null',
    isSubclass: 0,
    benClassIdSub: 6,
    benClassNameSub: 'null',
    isCustom: 0,
    procedureId: 100,
    code: 120,
    description: "Periodic oral eval",
    shortDescription: "Periodic oral eval",
    dateFrom: new Date("1970-01-01T00:00:00-05:00"),
    dateTo: null,
    serviceType: 10921,
    serviceTypeName: "Oral Evaluation",
    neddCoverage: 11001,
    neddCoverageName: "NEDD Covered",
    ageLow: 2,
    ageHigh: 5,
    treatmentArea: 150,
    treatmentAreaName: 'null',
    treatmentAreaDetailList: 'null'
}
export const mockProcedure3: Procedure =
{
    id: 3,
    benClassId: 5,
    benClassName: 'null',
    isSubclass: 0,
    benClassIdSub: 6,
    benClassNameSub: 'null',
    isCustom: 0,
    procedureId: 100,
    code: 200,
    description: "Periodic oral eval",
    shortDescription: "Periodic oral eval",
    dateFrom: new Date("1970-01-01T00:00:00-05:00"),
    dateTo: null,
    serviceType: 10921,
    serviceTypeName: "Oral Evaluation",
    neddCoverage: 11001,
    neddCoverageName: "NEDD Covered",
    ageLow: 2,
    ageHigh: 5,
    treatmentArea: 150,
    treatmentAreaName: 'null',
    treatmentAreaDetailList: 'null'
}
export const mockProcedure4: Procedure =
{
    id: 4,
    benClassId: 5,
    benClassName: 'null',
    isSubclass: 0,
    benClassIdSub: 6,
    benClassNameSub: 'null',
    isCustom: 0,
    procedureId: 100,
    code: 200,
    description: "Periodic oral eval",
    shortDescription: "Periodic oral eval",
    dateFrom: new Date("1970-01-01T00:00:00-05:00"),
    dateTo: null,
    serviceType: 10921,
    serviceTypeName: "Oral Evaluation",
    neddCoverage: 11001,
    neddCoverageName: "NEDD Covered",
    ageLow: 2,
    ageHigh: 5,
    treatmentArea: 150,
    treatmentAreaName: 'null',
    treatmentAreaDetailList: 'null'
}

export const mockProcedureAgeLimit: IProcedureAgeLimit =
{
    id: 4,
    benClassId: 5,
    benClassName: 'null',
    isSubclass: 0,
    benClassIdSub: 6,
    benClassNameSub: 'null',
    isCustom: 0,
    procedureId: 100,
    code: 200,
    description: "Periodic oral eval",
    shortDescription: "Periodic oral eval",
    dateFrom: new Date("1970-01-01T00:00:00-05:00"),
    dateTo: null,
    serviceType: 10921,
    serviceTypeName: "Oral Evaluation",
    neddCoverage: 11001,
    neddCoverageName: "NEDD Covered",
    ageLimits: [
        {
            ageLow: 2,
            ageHigh: 6
        },
        {
            ageLow: 8,
            ageHigh: 10
        }
    ],
    treatmentArea: 150,
    treatmentAreaName: 'null',
    treatmentAreaDetailList: 'null'
}

export const mockSubClassData = {
    "id": 216,
    "description": "Benefit Class 4433",
    "subClassCount": 0,
    "benClassType": 11302,
    "neddCoverage": 11001,
    "neddCoverageName": "NEDD Covered",
    "effectiveDate": "2019-02-12T00:00:00-05:00",
    "termDate": "2019-03-03T00:00:00-05:00",
    "isSubclass": 0,
    "status": "TERMINATED",
    "procedureCount": 1,
    "procedures": []
};

export const mockBenefitClassData = {
    id: 216,
    description: "Benefit Class 4433",
    subClassCount: 0,
    benClassType: 11301,
    neddCoverage: 11001,
    neddCoverageName: "NEDD Covered",
    effectiveDate: new Date("2019-02-12T00:00:00-05:00"),
    termDate: new Date("2019-03-03T00:00:00-05:00"),
    isSubclass: false,
    status: "TERMINATED",
    procedureCount: 1,
    procedures: []
};

export const mockProceduresData = [
    { data: mockProceduresList[0] },
    { data: mockProceduresList[1] },
    { data: mockProceduresList[2] },
    { data: mockProceduresList[3] },
    { data: mockProceduresList[4] },
]

export const mockForm: any = {
    value: {
        description: "ggg",
        benClassType: 11301,
        effectiveDate: 0,
        termDate: 0,
        isSubclass: 1
    }
};
